// All player-visible strings live here — switching language is a data change.
export const STR = {
  title: "ELEMENTAL TD",
  tagline: "Defend the rift. Master the elements.",
  play: "Play",
  howTo: "How to play",
  lives: "Lives",
  gold: "Gold",
  wave: "Wave",
  points: "Element Souls",
  startWave: "Start",
  startNow: "▶ Start now",
  waveIn: "Wave",
  neutralName: "Neutral Tower",
  neutralSub: "infuse with an element",
  singleDesc: "single target",
  splashDesc: "splash AoE",
  infuseLater: "infuse with any element",
  infuseInto: "Infuse with an element",
  orInfuse: "Or infuse with an element",
  soulEarned: "Element Soul earned — open ✦ to spend it!",
  noElements: "Earn an element soul first — clear 5 waves, then unlock an element",
  unlock: "Unlock",
  noSouls: "No element souls yet — clear 5 waves to earn one",
  elements: "Elements",
  build: "Build a tower",
  pureTowers: "Element towers",
  comboTowers: "Combination towers",
  upgrade: "Upgrade",
  sell: "Sell",
  fuse: "⚗ Fuse → Dual",
  fuseTriple: "⚗ Fuse → Triple",
  fuseHint: "Tap another tower to fuse (a different element, no overlap)",
  fuseBad: "Need a tower with a different element (no overlap, max 3)",
  fused: "Fused into",
  fuseNone: "No valid tower to fuse with yet",
  needLvlAll: "Level all its elements to",
  fusesInto: "⚗ Fuses into",
  fuseReadyTip: "Ready — you have a tower to fuse with",
  fuseNeedTip: "Need a",
  cancel: "Cancel",
  speed: "Speed",
  maxed: "Max level",
  locked: "Locked",
  needElement: "Need element lvl",
  cantAfford: "Not enough gold",
  blocked: "That would block the path!",
  cantBuildPath: "You can't build on the path",
  noPoints: "No element points",
  levelUp: "Level up",
  lvl: "Lv",
  close: "Close",
  next: "Next",
  win: "Victory!",
  winMsg: "You survived all 20 waves. Keep going in Endless?",
  endless: "Endless mode",
  levelDone: "Level",
  points: "points",
  totalPoints: "Total points",
  nextUnlocked: "✓ Next level unlocked!",
  campaignDone: "🏆 Campaign complete!",
  nextLevel: "Level",
  levelSelect: "Level select",
  chooseLevel: "Choose a level",
  lose: "The rift is overrun",
  loseMsg: "Too many creeps broke through.",
  retry: "Play again",
  levelWord: "Level",
  range: "Range",
  dmg: "Damage",
  rate: "Rate/s",
  effStrong: "Strong vs this wave",
  effWeak: "Resisted by this wave",
  bossLabel: "BOSS",
  strongVs: "strong vs",
  tutTitle: "How to play",
  tut: [
    "Creeps march along the winding path from the rift to your base. Don't let them reach it.",
    "Tap the grass beside the path to build a base tower: an ARROW tower (single target) or an ARTILLERY tower (splash damage). Tuck towers into the lanes so they hit creeps on several passes.",
    "Every 5 waves you clear earns one ELEMENT SOUL. Open ✦ ELEMENTS and spend a soul to UNLOCK an element (or level it up — level 3 takes 3 souls = 15 waves).",
    "Tap a neutral tower and INFUSE it with an element you've unlocked. Now it can be upgraded up to the element's level (max 3).",
    "FUSE towers to go deeper: two different element towers → a DUAL tower (15 combos); a dual + a third element → a TRIPLE tower (20 combos, blending all three effects). Each levels up to 3 once all its elements are leveled.",
    "Waves AUTO-START: 5 seconds after one is cleared the next begins. Hit ▶ Start now to skip the wait.",
    "Every wave has an element. The counter-cycle is Light › Darkness › Water › Fire › Nature › Earth › Light: use the element BEFORE a creep's element for big bonus damage — creeps are nearly IMMUNE to the element after theirs, so you must diversify. Levels run 50 waves, each tougher.",
  ],
  got: "Got it",
};
